### ISSUE TITLE
pip install from requirements.txt

### ISSUE THREAD

**Issue by xwu0226** [IBM/MAX-Places365-CNN#9]
Example PR:
https://github.com/IBM/MAX-Review-Text-Generator/pull/7

**Comment by bdwyer2** [comment]
Is this really practical because we are downloading torchvision from pytorch.org instead of pypi?

**Comment by kommalapatinaveenkumar** [comment]
pip install install-requires
pip install requirements.txt

**Comment by asan645** [comment]
pip install install-requires
 pip install -r requirements.txt
